"""Build a draft model for a KEGG species from the reference artefacts (step 3b.4).

Ports the **organism-ID** path of RAVEN ``getKEGGModelForOrganism`` (the branch
taken when no FASTA file is given). For an organism already annotated in KEGG it
needs no homology search: take the organism's gene↔KO assignments, map KO→reaction
against the gene-free reference model, OR-join the organism's genes into each
reaction's GPR, and keep the reactions that end up with genes (plus spontaneous
reactions, optionally). The HMM/FASTA path is step 3b.5 (:mod:`.query`).

Consumes the 3b.2 artefacts: the gene-free reference ``cobra.Model`` plus the
``ko_reaction``, ``organism_gene_ko`` and ``rxn_flags`` tables. The KO→reaction
mapping is taken from the ``ko_reaction`` table (a lossless published artefact)
rather than from the reference model's annotations, so it does not depend on KEGG
annotations surviving an SBML round-trip.

Domain mode (``organism_id`` = ``"eukaryotes"``/``"prokaryotes"``) keeps the genes
of every organism in that domain; it needs the KEGG ``taxonomy`` file. Unlike
RAVEN, this uses the domain classification directly rather than the full
``getPhylDist`` distance matrix — the matrix existed for per-organism HMM
subsampling, which our fixed prok90/euk90 libraries (3b.3) make unnecessary.
"""
from __future__ import annotations

from pathlib import Path

import cobra
import pandas as pd

from raven_toolbox.io.yaml import read_yaml_model
from raven_toolbox.reconstruction.kegg.assemble import _DOMAINS, assemble_model_from_ko_genes
from raven_toolbox.reconstruction.kegg.parse import _resolve_artefact, read_kegg_table
from raven_toolbox.reconstruction.kegg.taxonomy import organisms_in_domain

_NOTE = "Included by get_kegg_model_for_organism (no HMMs)"


def get_kegg_model_for_organism(
    organism_id: str,
    reference_model: cobra.Model,
    ko_reaction: pd.DataFrame,
    organism_gene_ko: pd.DataFrame,
    *,
    rxn_flags: pd.DataFrame | None = None,
    taxonomy: str | Path | None = None,
    keep_spontaneous: bool = True,
    keep_undefined_stoich: bool = True,
    keep_incomplete: bool = True,
    keep_general: bool = False,
) -> cobra.Model:
    """Reconstruct a draft model for a KEGG species from its KO annotations.

    Parameters
    ----------
    organism_id
        Three/four-letter KEGG organism code (e.g. ``"eco"``), or
        ``"eukaryotes"``/``"prokaryotes"`` for a whole-domain model (requires
        ``taxonomy``). Matched case-insensitively.
    reference_model
        The gene-free KEGG reference model (from :func:`build_reference_model`).
    ko_reaction, organism_gene_ko, rxn_flags
        The relational tables from :func:`build_kegg_tables` (or read back with
        :func:`read_kegg_table`).
    taxonomy
        Path to the KEGG ``taxonomy`` file; required only for domain mode.
    keep_spontaneous, keep_undefined_stoich, keep_incomplete, keep_general
        Quality filters (RAVEN's ``keep*``). A reaction flagged in ``rxn_flags``
        is dropped unless its keep flag is set; this takes precedence over having
        genes. Spontaneous reactions are additionally kept *without* genes when
        ``keep_spontaneous`` is true.

    Returns
    -------
    cobra.Model
        A copy of the reference restricted to the organism's reactions, with GPRs
        built and ``kegg.genes`` annotations on the genes.
    """
    org = organism_id.lower()
    if org in _DOMAINS:
        if taxonomy is None:
            raise ValueError(
                f"Domain mode ({organism_id!r}) needs the KEGG taxonomy file; "
                "pass taxonomy=."
            )
        members = organisms_in_domain(taxonomy, org)
        rows = organism_gene_ko[organism_gene_ko["organism"].str.lower().isin(members)]
    else:
        known = set(organism_gene_ko["organism"].str.lower())
        if org not in known:
            raise ValueError(
                f"Organism '{organism_id}' has no genes in organism_gene_ko. "
                f"Provide a KEGG species code present in the table."
            )
        rows = organism_gene_ko[organism_gene_ko["organism"].str.lower() == org]

    ko_to_genes: dict[str, list[str]] = {}
    for org_code, gene, ko in zip(rows["organism"], rows["gene"], rows["ko"], strict=True):
        # In domain mode genes from different organisms can share a bare id;
        # qualify with the organism so they stay distinct.
        gene_id = gene if org not in _DOMAINS else f"{org_code.lower()}:{gene}"
        ko_to_genes.setdefault(ko, []).append(gene_id)

    model, _ = assemble_model_from_ko_genes(
        reference_model,
        ko_reaction,
        ko_to_genes,
        rxn_flags=rxn_flags,
        keep_spontaneous=keep_spontaneous,
        keep_undefined_stoich=keep_undefined_stoich,
        keep_incomplete=keep_incomplete,
        keep_general=keep_general,
        model_id=organism_id,
        model_name=f"Generated by get_kegg_model_for_organism for {organism_id}",
        note=_NOTE,
    )
    for gene in model.genes:
        # Species mode: bare gene id -> organism:gene. Domain mode: already
        # organism-qualified.
        value = gene.id if ":" in gene.id else f"{org}:{gene.id}"
        gene.annotation["kegg.genes"] = value
    return model


def get_kegg_model_for_organism_from_artefacts(
    organism_id: str,
    artefact_dir: str | Path | None = None,
    *,
    version: str | None = None,
    taxonomy: str | Path | None = None,
    **kwargs,
) -> cobra.Model:
    """Load the published 3b.2 artefacts from ``artefact_dir`` and build the model.

    Reads ``reference_model.yml.gz`` and the ``ko_reaction``/``organism_gene_ko``/
    ``rxn_flags`` gzipped-TSV tables, then calls :func:`get_kegg_model_for_organism`.
    If ``artefact_dir`` is ``None`` the published artefacts are fetched/cached via
    :func:`raven_toolbox.data.ensure_kegg_data` (``version`` selects the release).

    For a whole-domain model (``organism_id`` = ``"prokaryotes"``/``"eukaryotes"``)
    the KEGG ``taxonomy`` artefact is resolved automatically — from ``artefact_dir``
    if present, otherwise fetched via :func:`raven_toolbox.data.ensure_kegg_taxonomy`
    (it is a separate artefact, not part of the core set) — unless an explicit
    ``taxonomy`` path is given.
    """
    if artefact_dir is None:
        from raven_toolbox.data import ensure_kegg_data

        artefact_dir = ensure_kegg_data(version=version)
    artefact_dir = Path(artefact_dir)
    if taxonomy is None and organism_id.lower() in _DOMAINS:
        try:
            taxonomy = _resolve_artefact(artefact_dir, "taxonomy.gz")
        except FileNotFoundError:
            from raven_toolbox.data import ensure_kegg_taxonomy

            taxonomy = ensure_kegg_taxonomy(version=version)
    reference_model = read_yaml_model(_resolve_artefact(artefact_dir, "reference_model.yml.gz"))
    ko_reaction = read_kegg_table(_resolve_artefact(artefact_dir, "ko_reaction.tsv.gz"))
    organism_gene_ko = read_kegg_table(_resolve_artefact(artefact_dir, "organism_gene_ko.tsv.gz"))
    rxn_flags = read_kegg_table(_resolve_artefact(artefact_dir, "rxn_flags.tsv.gz"))
    return get_kegg_model_for_organism(
        organism_id,
        reference_model,
        ko_reaction,
        organism_gene_ko,
        rxn_flags=rxn_flags,
        taxonomy=taxonomy,
        **kwargs,
    )
